### ISSUE TITLE
Strange color? outputs

### ISSUE THREAD

**Issue by peterbe** [rehandalal/therapist#32] opened 2018-09-06 12:57 UTC
```
▶ therapist install
#{yellow}There is an existing pre-commit hook.
#{reset_all}Therapist can preserve this legacy hook and run it before the Therapist pre-commit hook.
Would you like to preserve this legacy hook? [Y/n]:
```

What's with the `#{yellow}` and `#{reset_all}` things?

**Comment by rehandalal** [comment] 2018-09-06 15:41
weird. those should be getting replaced by the appropriate terminal color characters.

**Comment by peterbe** [comment] 2018-09-06 17:04
Other colors worked. Like when I do a git commit that 
```
black..............................[SUCCESS]
```
...or whatever it says, works.

**Comment by rehandalal** [comment] 2019-05-11 01:50
Could not reproduce. Closing for now.

**Closed by rehandalal** 2019-05-11 01:50 UTC
